# Async using Spring Security 5.1:
spring:
  security:
    oauth2:
      client:
        registration:
          apigee:
            authorization-grant-type: client_credentials
            client-id: ${apigee.client_id}
            client-secret: ${apigee.client_secret}
        provider:
          apigee:
            token-uri: https://mparaz-eval-test.apigee.net/oauth/client_credential/accesstoken

# Sync using Spring Security OAuth:
sync:
  apigee:
    grantType: client_credentials
    clientId: ${apigee.client_id}
    clientSecret: ${apigee.client_secret}
    accessTokenUri: https://mparaz-eval-test.apigee.net/oauth/client_credential/accesstoken
    scope: custom_mod
